### ISSUE TITLE
Proposal to add log colorization feature

### ISSUE THREAD

**Issue by selemondev** [timb-103/nuxt-mongodb#1]
It can be quite challenging to quickly identify and differentiate different types of logs produced by the `nuxt-mongodb` module. To fix this, I propose the implementation of a log colorization feature.

**Feature request**:

1. **Connecting Logs (Blue)** : Logs related to establishing connections or initiating processes can be displayed in a blue color.

2. **Connected Logs (Green)**: Logs indicating successful connections can be displayed in a green color.

3. **Error Logs (Red)** : Logs indicating errors can be displayed in a red color.

**Comment by timb-103** [comment]
Sounds good to me! Will try and get it done asap. Feel free to add a PR if you want to speed it up :)

**Comment by selemondev** [comment]
OK.

**Comment by timb-103** [comment]
Has been added into v1.0.4!
