### ISSUE TITLE
Integrate with unstorage 

### ISSUE THREAD

**Issue by harlan-zw** [timb-103/nuxt-mongodb#4]
See https://nuxt.com/docs/guide/directory-structure/server#server-storage

Unstorage already provides support for MongoDB. Having a module specifically for it is okay as it can expand the API and DX, making it more user-friendly.

But re-implementing the core feature may be a waste of effort.

I'd suggest keeping the API the same but use unstorage.

**Comment by domsen123** [comment]
@harlan-zw 
unstorage == key-value store
this module != key-value store

am I wrong?
